# Generated by Django 4.1 on 2022-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_area_office_alter_profile_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="personal email"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="phone number"),
        ),
    ]
