# Generated by Django 4.1 on 2022-08-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1, unique=True, verbose_name="feeder band")),
                (
                    "description",
                    models.CharField(blank=True, max_length=1, null=True, verbose_name="band description"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feeder",
            name="band",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.band"
            ),
        ),
    ]
