# Generated by Django 4.1 on 2022-08-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_band_feeder_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="hos",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="hours of supply"),
            preserve_default=False,
        ),
    ]
