# Generated by Django 4.1 on 2022-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_band_hos"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeder",
            name="average_load_mw",
            field=models.FloatField(blank=True, null=True, verbose_name="average load (mw)"),
        ),
        migrations.AddField(
            model_name="feeder",
            name="peak_load_mw",
            field=models.FloatField(blank=True, null=True, verbose_name="peak load (mw)"),
        ),
    ]
