# Generated by Django 4.1 on 2022-08-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_feeder_average_load_mw_feeder_peak_load_mw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powertransformer",
            name="voltageRating",
            field=models.CharField(
                choices=[("330/132KV", "330/132KV"), ("132/33KV", "132/33KV"), ("33/11KV", "33/11KV")],
                default="33/11KV",
                max_length=9,
            ),
        ),
    ]
