# Generated by Django 4.1 on 2022-08-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_powertransformer_voltagerating"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeder",
            name="voltage_level",
            field=models.CharField(
                choices=[("11", "11KV"), ("33", "33KV")], default="33KV", max_length=4, verbose_name="voltage level"
            ),
            preserve_default=False,
        ),
    ]
