# Generated by Django 4.1 on 2022-08-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_feeder_voltage_level"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="powertransformer",
            unique_together={("name", "station")},
        ),
    ]
