# Generated by Django 3.2.15 on 2022-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_powertransformer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='short name'),
        ),
    ]
