# Generated by Django 3.2.15 on 2022-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_station_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='short name'),
        ),
    ]
