# Generated by Django 4.1 on 2022-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loadreading",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L/S", "LOAD SHEDDING"),
                    ("O/S", "OUT OF SERVICE"),
                    ("F/C", "FREQUENCY CONTROL"),
                    ("S/C", "SYSTEM COLLAPSE"),
                    ("O/F", "FAULT"),
                    ("P/O", "PLANNED OUTAGE"),
                    ("IN", "IN CIRCUIT"),
                ],
                max_length=3,
                null=True,
                verbose_name="feeder status",
            ),
        ),
    ]
