# Generated by Django 4.1 on 2022-08-25 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_powertransformer_unique_together"),
        ("dispatch", "0002_alter_loadreading_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForcedOutage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time_out", models.DateTimeField(verbose_name="time out")),
                ("time_in", models.DateTimeField(blank=True, null=True, verbose_name="time in")),
                ("relay_indicator", models.CharField(max_length=10, verbose_name="relay indicator")),
                (
                    "induced_by",
                    models.CharField(
                        choices=[("KAEDCO", "KAEDCO"), ("GRID", "GRID")], max_length=10, verbose_name="induced by"
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255, null=True, verbose_name="remark")),
                (
                    "feeder",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.feeder"
                    ),
                ),
            ],
        ),
    ]
