# Generated by Django 4.1 on 2022-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0003_forcedoutage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forcedoutage",
            name="induced_by",
            field=models.CharField(
                blank=True,
                choices=[("KAEDCO", "KAEDCO"), ("GRID", "GRID")],
                max_length=10,
                null=True,
                verbose_name="induced by",
            ),
        ),
    ]
