# Generated by Django 4.1 on 2022-08-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0004_alter_forcedoutage_induced_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forcedoutage",
            name="relay_indicator",
            field=models.CharField(
                choices=[
                    ("O/C", "Over Current"),
                    ("E/F", "Earth Fault"),
                    ("O/C & E/F", "Over Current & Earth Fault"),
                    ("O/S", "Out of Service"),
                    ("F/C", "Frequency Control"),
                ],
                max_length=10,
                verbose_name="relay indicator",
            ),
        ),
    ]
