# Generated by Django 3.2.15 on 2022-08-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_auto_20220825_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadreading',
            old_name='load_amps',
            new_name='load_mw',
        ),
    ]
