# Generated by Django 3.2.15 on 2022-08-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0007_rename_load_amps_loadreading_load_mw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadreading',
            name='allocation_mw',
        ),
        migrations.RemoveField(
            model_name='loadreading',
            name='generation_mw',
        ),
    ]
