# Generated by Django 3.2.15 on 2022-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_auto_20220826_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('allocation_mw', models.FloatField(verbose_name='allocation (mw')),
                ('generation_mw', models.FloatField(verbose_name='generation (mw')),
                ('status', models.CharField(choices=[('IN CIRCUIT', 'In Circuit'), ('BLACKOUT', 'Blackout')], max_length=10, verbose_name='grid status')),
            ],
        ),
    ]
