# Generated by Django 3.2.15 on 2022-09-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_grid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='status',
            field=models.CharField(choices=[('IN_CIRCUIT', 'IN CIRCUIT'), ('BLACKOUT', 'BLACKOUT')], default='IN_CIRCUIT', max_length=10, verbose_name='grid status'),
        ),
    ]
