# Generated by Django 3.2.15 on 2022-09-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_auto_20220912_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='allocation_mw',
            field=models.FloatField(default=0, verbose_name='allocation (MW)'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='generation_mw',
            field=models.FloatField(default=0, verbose_name='generation (MW)'),
        ),
    ]
