# Generated by Django 4.1 on 2022-08-20 11:11
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CITextExtension()
    ]
