# Generated by Django 4.1 on 2022-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="staff_id",
            field=models.PositiveIntegerField(
                error_messages={"unique": "A user with that staff id already exists."},
                help_text="Required. 12 characters or fewer. Digits only",
                unique=True,
                verbose_name="staff id",
            ),
        ),
    ]
