# Generated by Django 4.1 on 2022-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_staff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="other_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="other name"),
        ),
    ]
